version: '3'
services:
  php:
    build: php
    container_name: magento-php
    ports:
      - 9000:9000
    volumes:
      - magento-data:/var/www/html
      - ${MAGENTO_EXTENSION_PATH:-./klickly-magento2-extension}:/var/www/html/app/code/Klickly/Extension/
    networks:
      - appnet
    env_file:
      - .env
  nginx:
    image: nginx:1.11
    container_name: magento-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - magento-data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - appnet
    links:
      - php
    env_file:
      - .env
  db:
    image: mysql:5.7
    container_name: magento-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - appnet
    env_file:
      - .env

volumes:
  db_data:
  magento-data:

networks:
  appnet:
    driver: "bridge"