#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.3.0}
WITH_EXTENSION=${3:-false}

if ! type brew > /dev/null; then
  echo "Homerbrew is not installed. Installing..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if ! type docker > /dev/null; then
  echo "Docker is not installed. Installing..."
  brew cask install docker
fi

if [ ! -d "Magento-Shops" ]; then
  mkdir ~/Magento-Shops
fi

cd ~/Magento-Shops

if [ -d "$DOMAIN" ]; then
  echo "Domain already in use, please specify another and try again"
  return 0;
fi

mkdir ~/Magento-Shops/$DOMAIN
cd ~/Magento-Shops/$DOMAIN

curl -s https://raw.githubusercontent.com/klickly/klickly-docker-magento/master/lib/template|bash -s - magento-2
bin/download $VERSION

echo "Your system password has been requested to add an entry to /etc/hosts..."
echo "127.0.0.1 $DOMAIN" | sudo tee -a /etc/hosts

bin/setup $DOMAIN $WITH_EXTENSION